spring:
  profiles:
    active:
    - dev
---
spring:
  profiles:  dev
    active:
    name: config-server-dev
---
spring:
  profiles:  test
  application:
    name:  config-server-test
---
spring:
  profiles:  aaa
  application:
    name:  config-server-abc
